### ISSUE TITLE
astroid misforms email addresses

### ISSUE THREAD

**Issue by emdete** [gauteh/astroid#102]
if an email adress is formed with an 

    ?utf-8?B?SM....Vw?= <bla@foo.bar>

the first part is not considered a single element and not put into " when containing a , while composing and then sending mails. if the part contains a , it leads to wrong local emails which is quite ugly.

**Comment by gauteh** [comment]
There has to be a gmime way to escape the string correctly. The message
being composed is by definition UTF8, so the user must make sure the editor
is in UTF8 mode.

So the final string should consist of utf chars, and any special chars like
, and " need to be escaped. The addeesses are encoded in the composemessage
class before sending or saving.

Den tirsdag 1. mars 2016 skrev M. Dietrich <notifications@github.com>
følgende:

**Comment by emdete** [comment]
i disagree: " and , must not be escaped but when switching back to normal there should be a " around the decoded string in case it contains a ,

**Comment by gauteh** [comment]
M. Dietrich writes on March 2, 2016 14:52:
> i disagree: " and , must not be escaped but when switching back to normal there should be a " around the decoded string in case it contains a ,

I think it needs to be, otherwise it is not parsable by gmime - this is
probably what causes the problem.

**Comment by emdete** [comment]
gmime can parse the mail fine. it shows correct in the thread view. problem is when it comes to replying. then the adress is not properly quoted.

**Comment by emdete** [comment]
i just managed to make mutt work again and replied on that very mail. mutt works correctly on the addresses and sets the " on the correct location to quote the address properly.

**Comment by gauteh** [comment]
M. Dietrich writes on March 2, 2016 15:43:
> i just managed to make mutt work again and replied on that very mail. mutt works correctly on the addresses and sets the " on the correct location to quote the address properly.

Maybe there is an error in how we build the addresslist, it would be
interesting to see the output of Address::str() contra AddressList::str().

**Comment by gauteh** [comment]
Gaute Hope writes on March 2, 2016 16:14:
> M. Dietrich writes on March 2, 2016 15:43:
>> i just managed to make mutt work again and replied on that very mail. mutt works correctly on the addresses and sets the " on the correct location to quote the address properly.
> 
> Maybe there is an error in how we build the addresslist, it would be
> interesting to see the output of Address::str() contra AddressList::str().
> 

Please test #104: Would be great if you could test it on a other
addresses too, to make sure it doesn't introduce any regressions.

**Comment by gauteh** [comment]
Fixed.
