### ISSUE TITLE
if astroid closes composed emails should be saved as draft

### ISSUE THREAD

**Issue by emdete** [gauteh/astroid#103]
if you have windows where you composed emails and quit astroid the email should be saved as draft without further request.

**Comment by gauteh** [comment]
Fixed.

**Comment by ff2000** [comment]
Just an idea: This would be handy on segfault/abort/kill/..., too. -> signal.h

**Comment by gauteh** [comment]
ff2000 writes on March 4, 2016 9:06:
> Just an idea: This would be handy on segfault/abort/kill/..., too. -> signal.h

Yes, I'd say it is a little low pri though (esp abort and kill). On a
side note, if astroid gets killed while editing you will usually be able
to find your draft in ~/.cache/astroid (it might be worth notifying the
user on start-up that there are existing 'auto-saved' drafts here). I
guess vim often backs up stuff too.
