### ISSUE TITLE
[wishlist] opening an URL without a mouse

### ISSUE THREAD

**Issue by apm256** [gauteh/astroid#108]
Astroid is fully usable without a mouse, except when I have to open an URL included in a message.
Some "mouseless" way to open an URL would be great. For instance, an hint-like feature like vimperator/qutebrowser/dwb/..., or the ability to select a link then hit 'enter',...

**Comment by apm256** [comment]
Sorry, I've just found that this is already possible by hitting "Tab" then "Alt-Enter".

**Comment by gauteh** [comment]
Cool. Probably something that should go in the wiki!

Den onsdag 23. mars 2016 skrev apm256 <notifications@github.com> følgende:

**Comment by mardukbp** [comment]
This feature is seriously missing. In mu4e each URL is assigned a number and then you can visit one of them with e.g. `g 3`. The Tab method is very slow. I request this issue to be reopened. Thank you for writing this awesome email client!

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 10, 2016 22:56:
> This feature is seriously missing. In mu4e each URL is assigned a number and then you can visit one of them with e.g. `g 3`. The Tab method is very slow. I request this issue to be reopened. Thank you for writing this awesome email client!
> 

Thanks, maybe there is a webkit-way / JS-way to do this? 

Otherwise I think we should iterate over all 'a href's in the body,
assign a number which has to be added. Then, making the keybindings
should not be too hard.

**Comment by mardukbp** [comment]
I mostly receive plain text messages. In that case, a regexp search for "words" that begin with http(s):// will be enough.

For HTML emails it is also [simple](https://lists.webkit.org/pipermail/webkit-dev/2009-May/007523.html). Use `webkit_web_view_execute_script` to execute the following JS:

```js
for (var i=0; i < document.links.length; i++)
    { var li = document.links[i]; li.innerText = i+' '+li.innerText; };
```

The link location is in `document.links[i].href`.

**Comment by dnebauer** [comment]
> Sorry, I've just found that this is already possible by hitting "Tab" then "Alt-Enter".

That does not work for me. (Using version v0.10.2-60-g80253d28 on linux.) Have the key combinations changed or does this behaviour depend on a particular dependency I may be missing?

**Comment by gauteh** [comment]
dnebauer writes on januar 3, 2018 10:42:
>> Sorry, I've just found that this is already possible by hitting "Tab" then "Alt-Enter".
> 
> That does not work for me. (Using version v0.10.2-60-g80253d28 on linux.) Have the key combinations changed or does this behaviour depend on a particular dependency I may be missing?
> 

Might have stopped working when Tab was bound to jump-to-next-unread. 
You could unbind this key and and re-try.

**Comment by dnebauer** [comment]
> > > Sorry, I've just found that this is already possible by hitting "Tab" then "Alt-Enter".

> > That does not work for me. (Using version v0.10.2-60-g80253d28 on linux.) Have the key combinations changed or does this behaviour depend on a particular dependency I may be missing?

> Might have stopped working when Tab was bound to jump-to-next-unread.
> You could unbind this key and and re-try.

That was it. I unbound `thread_view.next_unread` and `Tab` began working as described above (as did `Alt-Enter` which was presumably working all along but had nothing to operate on). Thanks for the quick response. Is there any way to get `Shift-Tab` to jump backwards through links?

I assume this functionality is not exposed as a configurable binding, i.e., is 'hard-coded' to be bound to `Tab` and `Alt-Enter`?

**Comment by gauteh** [comment]
dnebauer writes on januar 3, 2018 11:54:
>> > > Sorry, I've just found that this is already possible by hitting "Tab" then "Alt-Enter".
> 
>> > That does not work for me. (Using version v0.10.2-60-g80253d28 on linux.) Have the key combinations changed or does this behaviour depend on a particular dependency I may be missing?
> 
>> Might have stopped working when Tab was bound to jump-to-next-unread.
>> You could unbind this key and and re-try.
> 
> That was it. I unbound `thread_view.next_unread` and `Tab` began working as described above (as did `Alt-Enter` which was presumably working all along but had nothing to operate on). Thanks for the quick response. Is there any way to get `Shift-Tab` to jump backwards through links?
> 
> I assume this functionality is not exposed as a configurable binding, i.e., is 'hard-coded' to be bound to `Tab` and `Alt-Enter`?

It might be Ctrl+Tab? It is a webkit binding, so it works becaouse we 
ignore it and let it pass through to webkit. So you have to figure out 
what key it is and unbind it from Astroid.

**Comment by dnebauer** [comment]
> It might be Ctrl+Tab? It is a webkit binding, so it works becaouse we
ignore it and let it pass through to webkit. So you have to figure out
what key it is and unbind it from Astroid.

In keybindings file change

```conf
thread_view.previous_unread=Key (false, false, (guint) GDK_KEY_ISO_Left_Tab) # Focus the previous unread message, default: Key (false, false, (guint) GDK_KEY_ISO_Left_Tab)
```

to

```rc
thread_view.previous_unread= # Focus the previous unread message, default: Key (false, false, (guint) GDK_KEY_ISO_Left_Tab)
```

and `Shift-Tab` will cycle backwards through html elements. Thanks again for your prompt help.
