### ISSUE TITLE
neovim integration

### ISSUE THREAD

**Issue by mkazlauskas** [gauteh/astroid#109]
It should be quite easy to make [neovim-gnome-terminal-wrapper](https://github.com/fmoralesc/neovim-gnome-terminal-wrapper) work instead of vim. I've tried it but were getting black screen. Any tips?

**Comment by gauteh** [comment]
Does neovim run in the terminal? Then if the terminal supports XEmbed it
should work. I think the interaction with the editor is a little gvim
specific now, but there is nothing  stopping me/us from making  it more
generic. Im kind of busy the next weeks  though, so I am not sure when I
get the chance to look at it.

Den torsdag 24. mars 2016 skrev Martynas <notifications@github.com>
følgende:

**Comment by mkazlauskas** [comment]
Yeah it does run it terminal. Since gvim seems to be a GUI app I though it would be appropriate to try and use a GUI wrapper. I'll a few more options to make it work even though I don't exactly know how astroid embeds the editor.

Excerpts from Gaute Hope's message of March 27, 2016 7:07 am:

**Comment by gauteh** [comment]
Astroid uses the XEmbed protocol, it passes a socket ID to the
plug-application which then renders itself into it. You are right that it
needs to be a gui application, but it also needs to support this protocol.
I dont know if gnome-terminal does, i would think so, but some terminal
surely does! Does not neovim have a gtk version?

Den søndag 27. mars 2016 skrev Martynas <notifications@github.com> følgende:

**Comment by mkazlauskas** [comment]
Thanks! I'll try [neovim/python-gui](https://github.com/neovim/python-gui) when I get some time.

Excerpts from Gaute Hope's message of March 28, 2016 6:02 am:

**Comment by gauteh** [comment]
Please test #119.

**Comment by gauteh** [comment]
Should work with #119.

**Comment by gauteh** [comment]
Check out: https://github.com/gauteh/astroid/wiki/Customizing-editor#neovim-through-st
