### ISSUE TITLE
Account signatures

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#115]
How can we predefine signatures per account?

I know signatures are boring and we should probably get rid of them. But in some context, they're mandatory (it's a professional obligation for me when writing in my capacity as an attorney to display some information such as the bar where I belong, etc.)

**Comment by gauteh** [comment]
Hugo Roy writes on April 23, 2016 10:07:
> How can we predefine signatures per account?
> 
> I know signatures are boring and we should probably get rid of them. But in some context, they're mandatory (it's a professional obligation for me when writing in my capacity as an attorney to display some information such as the bar where I belong, etc.)

It is relatively easy to just add a per-account signature when sending.
Some thoughts:

- Should there be a check-box enabling/disabling the signature (also
  keybinding)? (fairly easy)

- Should the signature be added to the draft, then we need some more
  complex logic to try and find and delete the original signature when
  changing accounts. (this could very easiy get messy: what if you
  change a small thing in the signature? what if you delete it? what if
  you want to re-add it?)

- Also, probably need to support inline and as_attachment signatures.

- I think it is useful to not always add the signature always: e.g. in a
  long thread with many replies it is just clutter. Could make an option
  for that and try to figure out if the signature has already been sent
  in this thread. With a check-box manually disabling/enabling it. For
  your work account this functionality could just be disabled.

**Comment by hugoroy** [comment]
Hi Gaute,

Let's try to sum up facts about signatures:

  - they're usually per account (e.g. you don't want the same signature
    for your personal account as for your professional account for
    instance)

  - they do not change and are supposedly the same for each messages
    sent from an account, so having them in the draft of the message
    itself does not seem relevant

  - sometimes the user expressly wants to add the signature, and
    sometimes the user doesn't care.



↪ avril 24, 2016 12:42 , Gaute Hope:
> It is relatively easy to just add a per-account signature when sending.
> Some thoughts:
> 
> - Should there be a check-box enabling/disabling the signature (also
>   keybinding)? (fairly easy)

I think this is good. Let's say I just wrote an email.

Now I want to change the account I'm sending it with. I can do this with
the keybinding or I can do this on the interface with the mouse.

Let's say I select my professional account, with which I always want the
signature. In that case I think it would be good to have an option in
the account saying that I want by default the signature to be on.

> - Should the signature be added to the draft, then we need some more
>   complex logic to try and find and delete the original signature when
>   changing accounts. (this could very easiy get messy: what if you
>   change a small thing in the signature? what if you delete it? what if
>   you want to re-add it?)

I think that it's not very useful as the signature isn't supposed to
change.  You can always add a signature manually in the draft if you
want to.

> 
> - Also, probably need to support inline and as_attachment signatures.

That's probably something to put as a config option rather than in the
interface.

> - I think it is useful to not always add the signature always: e.g. in a
>   long thread with many replies it is just clutter. Could make an option
>   for that and try to figure out if the signature has already been sent
>   in this thread. With a check-box manually disabling/enabling it. For
>   your work account this functionality could just be disabled.

Yes, that could make it clever. For instance I think it definitely makes
sense to add a signature when you start an email thread, not so much
when you reply to threads (especially if you already contributed).


Hugo


PS: I don't consider this high priority for my needs (for instance, I'd
much prefer to have emacs support before this, or encryption support). I
could also figure out a fast way to do this in the draft editor to get
around this limitation meanwhile.
