### ISSUE TITLE
Feature: hide long quotes

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#120]
One of the scripts I used in mutt is t-prot: http://www.escape.de/~tolot/mutt/ it allows to hide overly long email quotes (which is really great when you have people top-posting).

Ideally, very long email quotes should be hidden by default, for instance showing three dots on a grey background that the user can click to reveal the long quote.

IIRC, Github also uses something like this in issues comments.

**Comment by gauteh** [comment]
Hugo Roy writes on April 27, 2016 10:48:
> One of the scripts I used in mutt is t-prot: http://www.escape.de/~tolot/mutt/ it allows to hide overly long email quotes (which is really great when you have people top-posting).
> 
> Ideally, very long email quotes should be hidden by default, for instance showing three dots on a grey background that the user can click to reveal the long quote.
> 
> IIRC, Github also uses something like this in issues comments.

Related to #73.

**Comment by gauteh** [comment]
I think this is covered by #73.
