### ISSUE TITLE
Build dependencies missing

### ISSUE THREAD

**Issue by jeremiah** [gauteh/astroid#124]
The build instructions would likely be improved if there was information on what build dependencies are required to build astroid. I'm currently getting a message saying;

```
Checking for gtkmm-3.0 >= 3.10... no
gtkmm-3.0 >= 3.10 not found.
````

And on my system, there is lots of gtkmm to be found; 

```` 
$ sylph.jeremiahfoster.com:~/GitHub/astroid>  show gtkmm-3.0
8 results found.
Results 1-8:
100% libgtkmm-3.0-dbg - C++ wrappers for GTK+ (debug symbols)
98% libgtkmm-3.0-dev - C++ wrappers for GTK+ (development files)
92% libgtkmm-3.0-doc - C++ wrappers for GTK+ (documentation)
92% libgtkmm-3.0-1v5 - C++ wrappers for GTK+ (shared libraries)
72% libgtksourceviewmm-3.0-doc - C++ binding of GtkSourceView
71% libgtksourceviewmm-3.0-0v5 - C++ binding of GtkSourceView
69% libgtksourceviewmm-3.0-dbg - C++ binding of GtkSourceView - debugging symbols
68% libgtksourceviewmm-3.0-dev - C++ binding of GtkSourceView - development files
````

**Comment by gauteh** [comment]
Hi,

`gtkmm` is the official name of the package (http://www.gtkmm.org/en/).
But different distros ship it under different names. Some distros also
split binary parts of the package (the .so) and the headers in -dev
packages. But all of this varies, the only thing constant is the
official name. 

I think therefore that it is better to keep the build system to only use
gtkmm, and rather put distro-specific information in the wiki: https://github.com/gauteh/astroid/wiki/Compiling-and-Installing#distribution-specific-information

Please feel free to update the wiki if you think something is missing,
or could be useful to others.

In your case, unless you already figured it out, you probably need libgtkmm-3.0-dev.

Regards, gaute

**Comment by jeremiah** [comment]
Thanks for the reply. I'll assemble the dependencies I needed to get astroid running on my system and put that on the wiki. I'll leave this issue open until it is complete.

**Comment by gauteh** [comment]
Jeremiah C. Foster writes on May 2, 2016 11:30:
> Thanks for the reply. I'll assemble the dependencies I needed to get astroid running on my system and put that on the wiki. I'll leave this issue open until it is complete. 
> 

Ok, thanks for testing out astroid!

**Comment by jeremiah** [comment]
https://github.com/gauteh/astroid/wiki/Debian
