### ISSUE TITLE
Quoted emails issues

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#125]
If an email is quoted and there is no blank line between the quote and the response, then the response will be listed in the quote.

For instance in the email raw source:

```
> Hugo
Apr=C3=A8s avoir visit=C3=A9 le site ffdn.org, content d'avoir pu vous ai=
d=C3=A9!!!
```

the `> Hugo` is supposed to be the last line of the quoted email, the line after is supposed to be a response, but it shows up as:

![capture d ecran de 2016-05-02 01-15-37](https://cloud.githubusercontent.com/assets/1629771/14944927/6b3b6062-1003-11e6-8270-dc6f1c728d48.png)

**Comment by gauteh** [comment]
Hugo Roy writes on May 2, 2016 1:15:
> If an email is quoted and there is no blank line between the quote and the response, then the response will be listed in the quote.
> ```
>> Hugo
> Apr=C3=A8s avoir visit=C3=A9 le site ffdn.org, content d'avoir pu vous ai=
> d=C3=A9!!!
> ```
Should be fixed!
