### ISSUE TITLE
Editor showing black screen on reply and on new mail

### ISSUE THREAD

**Issue by jeremiah** [gauteh/astroid#127]
Hi,

When I hit "m" to create a new mail, or when I hit "G" to reply to an email, a new window pops up. That window is pure black. It may be possible that there is black lettering on a black background but its impossible for me to tell since everything is, well, black. 

I've changed editors in the astroid configuration and there was no difference in the black screen.

**Comment by gauteh** [comment]
Jeremiah C. Foster writes on May 3, 2016 21:16:
> Hi,
> 
> When I hit "m" to create a new mail, or when I hit "G" to reply to an email, a new window pops up. That window is pure black. It may be possible that there is black lettering on a black background but its impossible for me to tell since everything is, well, black. 
> 
> I've changed editors in the astroid configuration and there was no difference in the black screen.
> 

What's the configuration line you have in the config?

Does the editor appear if you try to press some keys?

Could you send a screenshot? Does this always happen?

**Comment by jeremiah** [comment]
What's the configuration line you have in the config?
````
   "editor": {                                                                                                                                                                                       
        "cmd": "emacs --parent-id %3 %1",                                                                                                                                                             
        "charset": "utf-8",                                                                                                                                                                           
        "save_draft_on_force_quit": "true"                                                                                                                                                            
    },     
````
Does the editor appear if you try to press some keys?

Nope. Tried that.

Could you send a screenshot? Does this always happen?

Always happens. 
![screenshot from 2016-05-03 22-13-10](https://cloud.githubusercontent.com/assets/5260/14996889/778a9822-117c-11e6-87fa-24dac74a886c.png)

**Comment by gauteh** [comment]
What version of emacs do you have?

**Comment by gauteh** [comment]
Could you send the full log from startup? It seems the editor doesn't attach properly.

**Comment by jeremiah** [comment]
I'm using emacs version 24.5.1

➜  ~ emacs --version
GNU Emacs 24.5.1

Here's the log file;

[info ] (11:20:04): welcome to astroid! - v0.5-141-g689e683b
[debug] (11:20:04): utf8: 1, UTF-8
[debug] (11:20:04): loading gtk..
[debug] (11:20:06): HOME: /home/jeremiah
[info ] (11:20:06): cf: loading: "/home/jeremiah/.config/astroid/config"
[info ] (11:20:06): cf: version: 5
[info ] (11:20:06): notmuch db: /home/jeremiah/Maildir
[info ] (11:20:06): date: init.
[info ] (11:20:06): ac: initializing accounts..
[info ] (11:20:06): ac: setup account: charlie for Jeremiah C. Foster (default: 1)
[info ] (11:20:06): global actions: set up.
[info ] (11:20:06): poll: setting up.
[debug] (11:20:06): poll: interval: 60
[debug] (11:20:06): poll: requested..
[warn ] (11:20:06): astroid: starting a new window..
[info ] (11:20:06): poll: polling: /home/jeremiah/.config/astroid/poll.sh
[info ] (11:20:06): db: open db read-only, waiting for lock..
[debug] (11:20:06): db: read-only got lock.
[debug] (11:20:06): db: open time: 1.08 ms.
[debug] (11:20:06): poll: revision before poll: 3667
[ERROR] (11:20:06): poll: poll script does not exist or is not a regular file.
[info ] (11:20:06): db: closing db.
[debug] (11:20:06): db: ro: waiting for lock to close..
[debug] (11:20:06): db: ro: closing..
[info ] (11:20:06): db: open db read-only, waiting for lock..
[debug] (11:20:06): db: read-only got lock.
[debug] (11:20:06): db: open time: 0.294 ms.
[info ] (11:20:06): db: loaded 7 tags.
[info ] (11:20:06): db: closing db.
[debug] (11:20:06): db: ro: waiting for lock to close..
[debug] (11:20:06): db: ro: closing..
[debug] (11:20:06): mw: init, id: 1
[info ] (11:20:06): astroid: got query: inbox: tag:inbox
[info ] (11:20:06): re: using installed resource: /usr/share/astroid/ui/no-mail.png
[debug] (11:20:06): pm: add pane
[info ] (11:20:06): db: open db read-only, waiting for lock..
[debug] (11:20:06): db: read-only got lock.
[debug] (11:20:06): db: open time: 0.529 ms.
[debug] (11:20:06): ql: refresh stats..
[debug] (11:20:06): mw: does not have focus, will not grab modal.
[debug] (11:20:06): mw: does not have focus, will not grab modal.
[debug] (11:20:06): mw: does not have focus, will not grab modal.
[info ] (11:20:06): db: closing db.
[debug] (11:20:06): db: ro: waiting for lock to close..
[debug] (11:20:06): db: ro: closing..
[info ] (11:20:07): poll: emitted poll state: 0
[info ] (11:20:07): poll: emitted poll state: 0
[debug] (11:20:07): ti: got refresh stats.
[debug] (11:20:07): ql: loaded 100 threads.
[debug] (11:20:07): ti: got refresh stats.

**Comment by gauteh** [comment]
It doesn't seem to be any attempts at composing or opening the editor in the log, did you include that?

**Comment by jeremiah** [comment]
How would I include the editor loading? I merely changed the config file and I thought that it would be picked up automagically.

**Comment by gauteh** [comment]
I meant, to include the full log from startup and including attempting
to start the editor. That is, the full log of:

1. starting astroid
2. pressing 'm' or something to start the composer

**Comment by jeremiah** [comment]
[astroid-log.txt](https://github.com/gauteh/astroid/files/251064/astroid-log.txt)

**Comment by jeremiah** [comment]
Looks like Glade is being called for some reason? Also, emacs is complaining that "standard input is not a tty"

**Comment by gauteh** [comment]
Jeremiah C. Foster writes on mai 5, 2016 21:34:
> Looks like Glade is being called for some reason? Also, emacs is complaining that "standard input is not a tty"
> 

Glade is ok: That is a glade file being loaded and rendered. I am more
worried about the:

- standard input is not a tty, and
- (astroid:31899): Gdk-CRITICAL **: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed

I guess your emacs is using gtk3? I saw some other stuff about gtk2 up
there.

I am installing debian virtual image now to see if I can reproduce the
issue. There are some example / demos of the gtk plugin socket
interface, eventually it would be interesting to see how well those
work for you.

**Comment by jeremiah** [comment]
> On 05 May 2016, at 23:13, Gaute Hope <notifications@github.com> wrote:
> 
> Jeremiah C. Foster writes on mai 5, 2016 21:34:
> > Looks like Glade is being called for some reason? Also, emacs is complaining that "standard input is not a tty"
> > 
> 
> Glade is ok: That is a glade file being loaded and rendered. I am more
> worried about the:
> 
> - standard input is not a tty, and
> - (astroid:31899): Gdk-CRITICAL **: gdk_window_get_window_type: assertion 'GDK_IS_WINDOW (window)' failed
> 
> I guess your emacs is using gtk3? I saw some other stuff about gtk2 up
> there.

I am using GNOME for sure but Emacs is being run without X Windows via the Emacs-nox package.

**Comment by gauteh** [comment]
Jeremiah C. Foster writes on mai 6, 2016 0:48:
>> On 05 May 2016, at 23:13, Gaute Hope <notifications@github.com> wrote:
>> 
>> Jeremiah C. Foster writes on mai 5, 2016 21:34:
>> I guess your emacs is using gtk3? I saw some other stuff about gtk2 up
>> there.
> 
> I am using GNOME for sure but Emacs is being run without X Windows via the Emacs-nox package.

You definetely need Emacs with X, but not necessarily gtk. 

If you want to run the nox version you need to run a terminal and then
launch emacs within it, like in:
https://github.com/gauteh/astroid/wiki/Customizing-editor#neovim-through-st

astroid embeds the editor via XEmbed: it creates a window inside astroid
and passes this socket to the editor (or other plugin-application). The
plugin then draws the window inside astroid.

The previous editor-line probably didn't work because you don't have
gvim installed (?).

-gaute

**Comment by jeremiah** [comment]
Nope, I don't have gvim installed. Thanks for letting me know about the Xorg requirement, I'll poke at that.
