### ISSUE TITLE
Polling does not refresh the message list when a message is gone

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#134]
I did the following experiment: 

1. Sent myself an email
2. Press P
3. Received new email
4. Deleted the email in gmail.com
5. Press P

The message is still there in astroid until I press $ to refresh the list. I think this should be done automatically.

**Comment by mardukbp** [comment]
I just set `save_sent` to `true` and now this problem is gone. I am thinking that when I receive the email it has the tag `inbox` and the sent email has the tag `sent`. When I delete the email from the INBOX outside of astroid and then poll, astroid only finds the message with tag `sent` and of course it is not shown in INBOX. I guess that something is not happening when there is no corresponding email with the tag `sent`.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 13, 2016 23:27:
> I just set `save_sent` to `true` and now this problem is gone. I am thinking that when I receive the email it has the tag `inbox` and the sent email has the tag `sent`. When I delete the email from the INBOX outside of astroid and then poll, astroid only finds the message with tag `sent` and of course it is not shown in INBOX. I guess that something is not happening when there is no corresponding email with the tag `sent`.

The message must match the query to show up / or be deleted from it. It
must have the same message id (both copies probably do), to be updated
in both queries (tag:inbox and tag:sent). 

Do you have a recent notmuch with lastmod: capabilities?

**Comment by gauteh** [comment]
Closing, since problem is gone.
