### ISSUE TITLE
The threading algorithm works incorrectly

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#135]
When I search for messages from a specific sender (e.g. john.smith@server.com) one of the results is a thread which contains messages sent in different years. Clearly, they do not belong to the same thread. 

Additionally, this thread contains a forward that someone sent me. The body of this message contains john.smith@server.com. Other than that, I do not understand what makes astroid think that this message belongs to the thread.

If necessary, I could provide the messages privately.  They are spam, but good for debugging purposes :)

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 13, 2016 22:54:
> When I search for messages from a specific sender (e.g. john.smith@server.com) one of the results is a thread which contains messages sent in different years. Clearly, they do not belong to the same thread. 
> 
> Additionally, this thread contains a forward that someone sent me. The body of this message contains john.smith@server.com, Other than that, I do not understand what makes astroid think that this message belongs to the thread.
> 
> If necessary, I could provide the messages privately.  They are spam, but good for debugging purposes :)

All threading and indexing is done by notmuch, so this has to be
submitted to notmuch. Either mailinglist or irc: #notmuch @ freenode.

**Comment by mardukbp** [comment]
Thanks! Good to know. I will take it to them.
