### ISSUE TITLE
After polling message list is not scrolled down

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#137]
Let us assume that astroid is running. I hit `P` and new messages arrive. However, I will not see them unless I scroll down to get to the top of the message list. This should happen automatically.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 14, 2016 11:28:
> Let us assume that astroid is running. I hit `P` and new messages arrive. However, I will not see them unless I scroll down to get to the top of the message list. This should happen automatically.
> 

Scroll to the top you mean? What if you are scrolled down already? It
would not make sense to move the cursor to the top then.

I think the only case we should scroll up is if the cursor is previously
focused on the top, and the new thread is added before it (threads may
be added to a query by changing tags).

**Comment by mardukbp** [comment]
> I think the only case we should scroll up is if the cursor is previously
> focused on the top, and the new thread is added before it

Yes. That is precisely the case I had in mind.
