### ISSUE TITLE
Search for words in thread view

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#141]
As far as I can tell, it is currently not possible to search for words when you open a thread. It would be very useful to have this functionality.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 20, 2016 22:53:
> As far as I can tell, it is currently not possible to search for words when you open a thread. It would be very useful to have this functionality.
> 

Yes, this has been on my list for-ever: please try #142.

**Comment by gauteh** [comment]
If you are unsure on how to test, have a look at: https://github.com/gauteh/astroid/wiki/Contributing#how-to-test-a-pull-request

**Comment by mardukbp** [comment]
Thanks! How does one move between search results? Like n and N in less.

I guess you are not using Xapian for this feature, because it did not
recognize a search term like "open a thread".

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 22, 2016 12:17:
> Thanks! How does one move between search results? Like n and N in less.

It says in the pull-request.
 
> I guess you are not using Xapian for this feature, because it did not
> recognize a search term like "open a thread".

No, I use webkit, case-insensitive, but you have to type exactly the
correct phrase.

**Comment by gauteh** [comment]
Merged.

**Comment by mardukbp** [comment]
It only remains to add this command to the help menu.

**Comment by gauteh** [comment]
No. It is automatically added.

**Comment by mardukbp** [comment]
Scratch that. I just saw it. However, there is something wrong with the
key for Cancel current search. It says 65307.

**Comment by gauteh** [comment]
fixed
