### ISSUE TITLE
Missing toggle flagged in Apply action to marked threads

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#143]
I marked several threads that are flagged and I would like to unflag them. Unfortunately `+` does not provide that option.

**Comment by gauteh** [comment]
Yes, it does: just press '*'. It will toggle the flagged tag. You could also use + and l and -flagged.

**Comment by mardukbp** [comment]
Oops, sorry I missed that. I would suggest that in the menu that appears
when pressing `+` it says Toggle flagged instead of just Flag.

**Comment by gauteh** [comment]
Already done.
