### ISSUE TITLE
Tag all messages in thread

### ISSUE THREAD

**Issue by mardukbp** [gauteh/astroid#146]
Say you were invited to an event on Facebook that you are not attending and everybody is commenting on the event and you receive all the comments in your INBOX. You would like to be able to select the thread and apply the `deleted` tag to all messages. I could not find a way to do it.

**Comment by gauteh** [comment]
Marduk Bolaños writes on mai 24, 2016 8:00:
> Say you were invited to an event on Facebook that you are not attending and everybody is commenting on the event and you receive all the comments in your INBOX. You would like to be able to select the thread and apply the `deleted` tag to all messages. I could not find a way to do it.

If you add do something to a thread in the thread-index it is done to
all the messages. Also, check out C-m for mute.

**Comment by mardukbp** [comment]
My problem was that each new message brought up the thread again. I just
muted it. Thanks.
