### ISSUE TITLE
Keybinding '=' and '-'

### ISSUE THREAD

**Issue by imiric** [gauteh/astroid#148]
Hi,

instead of the default `main_window.next_page=b` and `main_window.previous_page=B`, I'd like to rebind these to `=` (Equals) and `-` (Minus), respectively.

Currently, astroid fails to start when setting these with:

```
[debug] (11:44:22): ky: parsing line: main_window.next_page==
[ERROR] (11:44:22): ky: user bindings: too many parts in: main_window.next_page==
[debug] (11:44:22): ky: parsing line: main_window.previous_page=-
[ERROR] (11:44:22): key spec invalid: -
terminate called after throwing an instance of 'Astroid::keyspec_error'
  what():  invalid modifier in key spec
zsh: abort (core dumped)  astroid
```

I also tried with `Equals` and `Minus` with the same results.

Is this currently possible?

Thanks for your work.

Ivan

**Comment by gauteh** [comment]
Hi,

I just added the 'Equal' and 'Minus' key-specifiers, please pull latest
from git and try using them:

`main_window.next_page=Equal`

-gaute

Ivan Mirić writes on mai 26, 2016 11:45:

**Comment by imiric** [comment]
Excellent, works great!

Thanks again!
