### ISSUE TITLE
crash when using "tab" to complete a tag

### ISSUE THREAD

**Issue by apm256** [gauteh/astroid#15]
Hi gauteh,

Here is a small bug:
- choose a thread with a sufficient number of tags;
- press 'l';
- type the beginning of an existing tag;
- complete it with the "TAB" key (nice feature by the way, thanks for it!);
- then, type "," to add another tag.

Result: astroid crashes with the following trace:

```
[debug] (16:21:37): cb: completion: taking next match
(astroid:21057): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: basic_string::assign: __pos (which is 18446744073709551615) > this->size() (which is 24)
```

**Comment by gauteh** [comment]
Excerpts from apm256's message of February 10, 2015 16:24:
> Hi gauteh,
> 
> Here is a small bug:
> - choose a thread with a sufficient number of tags;
> - press 'l';
> - type the beginning of an existing tag;
> - complete it with the "TAB" key (nice feature by the way, thanks for it!);
> - then, type "," to add another tag.
> 
> Result: astroid crashes with the following trace:
> 
> ```
> [debug] (16:21:37): cb: completion: taking next match
> (astroid:21057): glibmm-ERROR **: 
> unhandled exception (type std::exception) in signal handler:
> what: basic_string::assign: __pos (which is 18446744073709551615) > this->size() (which is 24)
> ```

Hey, thanks, yeah - the problem goes away if you put a space after ','
before trying to complete again. It is still a bug though! (or perhaps
this is a slightly different bug..)

By the way, have you tried out any of the highlighting stuff or from
mathjax (e.g. the trace you included here should have highlighting,
which would make more sense if it was code of course).

gaute

**Comment by apm256** [comment]
Thank you for the tip!
I didn't try the highlighting features yet. I will let you know when I have done it.
