### ISSUE TITLE
Make Sass optional?

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#152]
I have heard that compiling astroid on Debian stable might prove difficult because of libsass-dev. If this is indeed the only library holding Debian stable users from installing astroid without the headache, I think it makes sense to make this optional and let ship astroid with a default css built at each release.

I was also told that compiling on centos is not easy because of outdated libraries.

What do you think?

**Comment by gauteh** [comment]
Hugo Roy writes on mai 30, 2016 17:16:
> I have heard that compiling astroid on Debian stable might prove difficult because of libsass-dev. If this is indeed the only library holding Debian stable users from installing astroid without the headache, I think it makes sense to make this optional and let ship astroid with a default css built at each release.
> 

Yes, we could make this optional. The best would be to have the css
generated on build in that case, is sassc or equivalent available? Then
we would require them to be available at build time.

Then we could add a build option --disable-libsass which tells the
resources to open the CSS and not the SCSS. That would make it more
flexible.

> I was also told that compiling on centos is not easy because of outdated libraries.

Outdated on CentOS I assume, depends on what.. if it is gtk it might be
harder.
 
> What do you think?

I agree, if we can make it work with some small changes that would be
good. I don't like including generated files, but if there is no other
option...

**Comment by gauteh** [comment]
Check #153.

**Comment by gauteh** [comment]
Gaute Hope writes on mai 30, 2016 17:26:
> Hugo Roy writes on mai 30, 2016 17:16:
>> I have heard that compiling astroid on Debian stable might prove difficult because of libsass-dev. If this is indeed the only library holding Debian stable users from installing astroid without the headache, I think it makes sense to make this optional and let ship astroid with a default css built at each release.
>> 
> 
> Yes, we could make this optional. The best would be to have the css
> generated on build in that case, is sassc or equivalent available? Then
> we would require them to be available at build time.
> 
> Then we could add a build option --disable-libsass which tells the
> resources to open the CSS and not the SCSS. That would make it more
> flexible.
> 

It seems that ruby-sass is available on debian: https://packages.debian.org/sid/ruby-sass
