### ISSUE TITLE
please support excluded tags

### ISSUE THREAD

**Issue by bremner** [gauteh/astroid#17]
I was playing with astroid today, and noticed that all my tag:deleted messages show up. The support
for excluded tags is in libnotmuch, so it would be nice to use it in astroid as well.

**Comment by gauteh** [comment]
Hi @bremner, thanks for the feedback, I noticed that the excluded tags support was not configurable, is there any way for me to access the notmuch config through libnotmuch?

**Comment by gauteh** [comment]
Fixed in fe50e50.

**Comment by bremner** [comment]
Gaute Hope <notifications@github.com> writes:

> Hi @bremner, thanks for the feedback, I noticed that the excluded tags
> support was not configurable, is there any way for me to access the
> notmuch config through libnotmuch?

No, the library currently doesn't have any config handling, sorry.  It
would be nice to have something in the future, keeping in mind the goal
of the library itself being stateless.

d

**Comment by gauteh** [comment]
Excerpts from bremner's message of April 27, 2015 15:36:
> Gaute Hope <notifications@github.com> writes:
> 
>> Hi @bremner, thanks for the feedback, I noticed that the excluded tags
>> support was not configurable, is there any way for me to access the
>> notmuch config through libnotmuch?
> 
> No, the library currently doesn't have any config handling, sorry.  It
> would be nice to have something in the future, keeping in mind the goal
> of the library itself being stateless.
> 

Yep. One option is to use a standard format (you might already be doing
that, I guess), so that something like boost could be used for parsing
it.
