### ISSUE TITLE
Escaped characters ("&amp;", "&apos;") don't display correctly in names

### ISSUE THREAD

**Issue by AshlynnInWonderland** [gauteh/astroid#18]
![escaped](https://cloud.githubusercontent.com/assets/8798637/8022231/90a06fac-0c92-11e5-80ff-5a56eb79eba6.png)

**Comment by AshlynnInWonderland** [comment]
![escaped](https://cloud.githubusercontent.com/assets/8798637/8022234/098404b0-0c93-11e5-8c61-f1b26c673406.png)
This also causes an issue with calculating the number of characters "allowed" in the title, causing it to clip with the next field.

**Comment by AshlynnInWonderland** [comment]
![escaped2.png](https://ptpb.pw/w5WI.png)
This also causes issues with calculating the number of characters shown in the title, as shown above.

**Comment by gauteh** [comment]
Hi, thanks for the report - could you check if dd84293 fixes the
issue?

**Comment by AshlynnInWonderland** [comment]
Yeah. Give me just a minute to update my install.

**Comment by AshlynnInWonderland** [comment]
It's working perfectly now. Thanks.
