### ISSUE TITLE
Can't open HTML parts

### ISSUE THREAD

**Issue by patternseek** [gauteh/astroid#19]
Hi,

I've just started using Astroid but I really like it so far, so thanks!

I can't seem to open HTML parts though. I've tried pressing o or enter with the email selected but nothing happens. I have "open_html_part_external": "true", in my config and i've set "open_external_link" to point to Firefox (also tried it with the default xdg-open which is installed an I've tested from the command line). I also have the default "external_open_cmd": "xdg-open". 

The text for the external part says "Alternative part (type: text/html) - potentially sketchy." but there doesn't seem to be any way to highlight or activate it.

I'm sure I'm missing something obvious but I've run out of ideas, sorry!

**Comment by gauteh** [comment]
Hi,

Thanks for testing out astroid!

Have you made sure that the HTML-part (greenish-box) thing is selected
before activating ('o' or enter) the element?

Use j/k after the email is selected to move to the next element inside
the email. j/k really only moves between the elements in the whole email
thread, while n/p quickly moves between the emails in a thread (with
several emails).

hope that works, if you have any suggestion on how i can make this
clearer it is much appreciated. you can also set open_html_part_external
to false and astroid will show the email inline when you 'activate' it.



patternseek writes on September 9, 2015 13:52:

**Comment by patternseek** [comment]
Ah yes that does the trick, thanks! I was using the arrow keys. Maybe the help page for the thread view could have an extra note after the info on j/k along the lines of "(including parts within a message)" or something to that effect?

Thanks again, I'm really liking the look of Astroid overall, it addresses most of the issues I've had with other notmuch clients very nicely.

**Comment by gauteh** [comment]
Refined it. Let me know if there are other issues.

**Comment by rothn** [comment]
This doesn't work for me. Pressing 'o' just opens up a search box no matter what I do.
