### ISSUE TITLE
Non-existing E-Mail file crashes astroid

### ISSUE THREAD

**Issue by hellerbarde** [gauteh/astroid#23]
When the DB is out of sync with the harddisk (mutt moved E-Mail file, but didn't tell notmuch), as soon as you try to open that message, astroid segfaults. 

Steps to reproduce:
1. remove/move E-Mail file in your maildir.
2. Try to open that particular Message in Astroid. 
3. Astroid crashes after printing in the console that the file does not exist. 

cheers!

**Comment by gauteh** [comment]
Hi! Test out latest git, it should no longer crash, but rather display
cached values (in notmuch) and then a warning as well.

**Comment by hellerbarde** [comment]
Works as advertised. :+1:
