### ISSUE TITLE
(AUR) failed to compile

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#27]
Tried to compile https://aur.archlinux.org/packages/astroid/ and failed. See the output: https://paste.cat/NHPPiM

**Comment by gauteh** [comment]
Hugo Roy writes on January 2, 2016 13:23:
> Tried to compile https://aur.archlinux.org/packages/astroid/ and failed. See the output: https://paste.cat/NHPPiM

Ouch, my bad. Should be fixed now.

**Comment by hugoroy** [comment]
Yes, it's fixed :-) thanks. Great to see this moving forward by the way
