### ISSUE TITLE
Crashing when applying action to marked threads

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#28]
Steps to reproduce:

1. Mark a few threads with `t`
2. Hit `+` to apply an action to marked threads
3. astroid crashes

Debug output:

```
[debug] (00:40:43): ky: ThreadIndex mode, handling: T (thread_index.toggle_marked_all)
[debug] (00:40:46): ky: Mode,  unknown key: 65505
[debug] (00:40:46): ky: ThreadIndex mode,  unknown key: 65505
[debug] (00:40:46): ky: MainWindow,  unknown key: 65505
[debug] (00:40:46): ky: Mode,  unknown key: +
[debug] (00:40:46): ky: ThreadIndex mode, handling: + (therad_index.multi)
[info ] (00:40:46): mode: starting multi key.

(astroid:7801): glibmm-ERROR **: 
unhandled exception (type std::exception) in signal handler:
what: std::bad_alloc

[1]    7801 trace trap (core dumped)  astroid
```

**Comment by hugoroy** [comment]
The output says "therad_index.multi" so I suppose it's just a typo :-)

**Comment by gauteh** [comment]
Hugo Roy writes on January 3, 2016 0:43:
> Steps to reproduce:
> 
> 1. Mark a few threads with `t`
>  2. Hit `+` to apply an action to marked threads
>  3. astroid crashes
> 
> Debug output:
> 
> ```
> [debug] (00:40:43): ky: ThreadIndex mode, handling: T (thread_index.toggle_marked_all)
> [debug] (00:40:46): ky: Mode,  unknown key: 65505
> [debug] (00:40:46): ky: ThreadIndex mode,  unknown key: 65505
> [debug] (00:40:46): ky: MainWindow,  unknown key: 65505
> [debug] (00:40:46): ky: Mode,  unknown key: +
> [debug] (00:40:46): ky: ThreadIndex mode, handling: + (therad_index.multi)
> [info ] (00:40:46): mode: starting multi key.
> 
> (astroid:7801): glibmm-ERROR **: 
> unhandled exception (type std::exception) in signal handler:
> what: std::bad_alloc

The multi_key keybinding has to have the same life span as the
class-instance, storing it in the class now. Hopefully works better?

**Comment by hugoroy** [comment]
Yes, this works now.

So, I suppose this can't be used to add an arbitrarily tag to several threads?

**Comment by gauteh** [comment]
Hugo Roy writes on January 3, 2016 21:50:
> Yes, this works now.
> 
> So, I suppose this can't be used to add an arbitrarily tag to several threads? 

Ideally, yes :) but, I haven't got that far yet.

**Comment by hugoroy** [comment]
No, of course :) I just wanted to make sure I wasn't missing something obvious.

This is already very usable!
