### ISSUE TITLE
Hooks and user's own macros?

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#29]
Related to issue #21 but this isn't stricly about keybindings but more about user-defined macros:

For instance, I'd like to reasign `a` to not only toggle the "inbox" tag but also to toggle an "archive" tag.

In mutt (the kz fork with notmuch support), the keybinding is actually a macro:
`macro index,pager   a       "<modify-labels-then-hide>-unread -inbox +archive<enter><sync-mailbox>"             "archive"`

Is this something that can already be done by the user like keybindings?

**Comment by gauteh** [comment]
There was a brief discussion about this in #25, on setting up
user-defined hooks.

It is currently not possible, but I was planning to allow Python hooks
to be configured. Or possibly just regular shell scripts. The script
could get the message id or thread id and do something with it, return
true or false and astroid will re-render the line depending on that.

In shell; just use regular notmuch commands to do whatever.
In python; use the notmuch python bindings - or just execute a notmuch
command.

Shell is way easier to implement.

This would have to be hooked into the keybindings somehow, I was
thinking maybe:

thread_index.hook(my-special-hook)=a

along with some pre-defined hooks that can be attached to other
(non-key) events?

I currently don't really have a command/macro system.

What do you think?

**Comment by hugoroy** [comment]
Well, I wouldn't need anything fancy and so using shell for notmuch commands would make me very  happy :-) / for instance:

`thread_index.hook(notmuch tag -inbox -unread +archive)=a`

**Comment by gauteh** [comment]
Hugo Roy writes on January 3, 2016 21:36:
> Well, I wouldn't need anything fancy and so using shell for notmuch commands would make me very  happy :-) / for instance:
> 
> `thread_index.hook(notmuch tag -inbox -unread +archive)=a`

Yeah, this seems like a good idea, but perhaps use something like:

  main_window.run
  thread_index.run
  thread_index.multi.run

with pre-defined arguments.

**Comment by hugoroy** [comment]
I don't know. That looks like another configuration file needed to pre-define the arguments. I think it's alright if it's not pre-defined. But I don't have strong arguments any way.

**Comment by gauteh** [comment]
What I mean is that you can configure e.g.:

`thread_index.run(notmuch tag -inbox -unread +archive)=a`

which will run the command with one argument which is the thread id of
the currently selected thread:

`notmuch tag -inbox -unread +archive thread:00000xxx`

but you could also use your own script:

`thread_index.run(~/.config/astroid/scripts/toggle_archive)=a`

where you use notmuch commands to check if it already is archived and
then do what you want.

so the command:
thread_index.run will be run with 'thread:0000xxx' as the first and only
argument.

thread_index.multi.run will run the command with one argument for each
thread so that the script that gets it can act on all of them.

In this way you can:

* create a script to toggle archive
* output the file (using notmuch commands) or do something with it, as in #36 (probably fixing that issue?)

you do not need another configuration file.

**Comment by hugoroy** [comment]
↪ janvier 4, 2016 10:18 , Gaute Hope:
> What I mean is that you can configure e.g.:
> 
> `thread_index.run(notmuch tag -inbox -unread +archive)=a`
> 
> which will run the command with one argument which is the thread id of
> the currently selected thread:
> 
> `notmuch tag -inbox -unread +archive thread:00000xxx`
> 
> but you could also use your own script:
> 
> `thread_index.run(~/.config/astroid/scripts/toggle_archive)=a`
> 
> where you use notmuch commands to check if it already is archived and
> then do what you want.

Okay, now I understand. Yes this is pretty much perfect I think :)


> In this way you can:
> 
> * create a script to toggle archive
> * output the file (using notmuch commands) or do something with it, as in #36 (probably fixing that issue?)

Yes, that looks like a very, very good start to enable this indeed.

**Comment by gauteh** [comment]
Once the parser for this is up I think the following commands
should also be supported:

(mode here is either 'main_window' (which works for all),
'thread_index', etc).

mode.search('query:asdfasdf')=keyspec
thread_index.toggle_tag('tag_a,tag_b')=keyspec
thread_view.toggle_tag('tag_a,tag_b')=keyspec

**Comment by gauteh** [comment]
Fixed in #76.

**Comment by hugoroy** [comment]
@gauteh any idea how to use something like 

```
thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
```

on an email in thread_view rather than on an whole thread?

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 21:15:
> @gauteh any idea how to use something like 
> 
> ```
> thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
> ```
> 
> on an email in thread_view rather than on an whole thread?

Not implemented yet, but is trivial. Could have a look at how it's done
in thread_index_list_view.cc.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 2, 2017 21:18:
> Hugo Roy writes on mars 2, 2017 21:15:
>> @gauteh any idea how to use something like 
>> 
>> ```
>> thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
>> ```
>> 
>> on an email in thread_view rather than on an whole thread?
> 
> Not implemented yet, but is trivial. Could have a look at how it's done
> in thread_index_list_view.cc.


Here's my gibberish attempt. I have no idea what I am doing :-)

https://github.com/astroidmail/astroid/pull/300

**Comment by gauteh** [comment]
Hugo Roy writes on mars 2, 2017 22:00:
> ↪ Gaute Hope / mars 2, 2017 21:18:
>> Hugo Roy writes on mars 2, 2017 21:15:
>>> @gauteh any idea how to use something like 
>>> 
>>> ```
>>> thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
>>> ```

By the way, you can replace that with:

> ```
> thread_index.run(hooks::toggle waiting %1)=w
> ```

I've merged your PR, could you please update the documentation on the
hooks in the wiki?

**Comment by mxmehl** [comment]
I've added an example in the wiki for thread_view.run using %2 as message ID

**Comment by hugoroy** [comment]
↪ Max / mars 7, 2017 13:27:
> I've added an example in the wiki for thread_view.run using %2 as message ID

Hm. It does not work for me. Am I missing something? I just put that in
my keybindings:


    # Toggle waiting tag
    thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
    thread_view.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w

It tags the whole thread instead of just the email indeed. But replacing
%1 by %2 for the thread_view does nothing (with latest master).

**Comment by gauteh** [comment]
Hugo Roy writes on mars 7, 2017 23:37:
> ↪ Max / mars 7, 2017 13:27:
>> I've added an example in the wiki for thread_view.run using %2 as message ID
> 
> Hm. It does not work for me. Am I missing something? I just put that in
> my keybindings:
> 
> 
>     # Toggle waiting tag
>     thread_index.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
>     thread_view.run(/home/hugo/.config/astroid/hooks/toggle waiting %1)=w
> 
> It tags the whole thread instead of just the email indeed. But replacing
> %1 by %2 for the thread_view does nothing (with latest master).

perhaps toggle expects a thread id and not a message id.

**Comment by hugoroy** [comment]
↪ Gaute Hope / mars 7, 2017 23:49:
> perhaps toggle expects a thread id and not a message id.

Of course :-)

There's probably a better way to do it, but until then:

https://github.com/hugoroy/.astroid/tree/master/hooks

Using togglemail and %2 works.

**Comment by mxmehl** [comment]
@hugoroy is this something where my wiki additions have been unclear, or just a random mistake?

**Comment by hugoroy** [comment]
↪ Max / mars 8, 2017 0:39:
> @hugoroy is this something where my wiki additions have been unclear, or just a random mistake?

Your unspam example is just fine and actually quite a useful one for
most people! :^)

But the wiki could benefit from having in addition a more simple example
with a hook on how to use %1 and/or %2.

**Comment by mxmehl** [comment]
Am 08.03.2017 um 00:41 schrieb Hugo Roy:
> But the wiki could benefit from having in addition a more simple example
> with a hook on how to use %1 and/or %2.

Agreed. Would you like to extend your toogle script and comment it a
bit? This is a really simple and useful hook.

**Comment by hugoroy** [comment]
↪ Max / mars 8, 2017 0:43:
> Agreed. Would you like to extend your toogle script and comment it a
> bit? This is a really simple and useful hook.

Done. But there's room for optimization I guess :)

**Comment by mxmehl** [comment]
> Done. But there's room for optimization I guess :)

Thanks! One question: should the second example have `thread_view.run` as keybinding?

**Comment by hugoroy** [comment]
↪ Max / mars 8, 2017 0:57:
> Thanks! One question: should the second example have `thread_view.run` as keybinding?  

Ha, of course. Well, I guess I have to go sleep :)
