### ISSUE TITLE
documentation: a tour of astroid which showcases and explains the possibilities

### ISSUE THREAD

**Issue by gauteh** [gauteh/astroid#34]
It would be great with a documentation page/tour or similar that goes through setting up astroid and using the possibilities.

**Comment by hugoroy** [comment]
Yes, definitely. I guess it would be alright to also include a little bit about notmuch as well so pepole can get set up with both (without trying to duplicate too much the efforts of documenting notmuch use itself).

I think that the Wiki could be a good place to start writing the content, etc. I'll see if I have some time to help with that.

**Comment by gauteh** [comment]
Definitely, great!

**Comment by gauteh** [comment]
Feel free to move the stubs into this kind of context, then this can be the official documentation and we dont need to keep several version maintained.

**Comment by gauteh** [comment]
Also, I guess it is not obvious to a complete new user how astroid only displays, edits and composes emails. It does not fetch, index or actually send them (I'm guessing notmuch has some pages for that).

**Comment by hugoroy** [comment]
I've written some general stuff about all this in https://github.com/gauteh/astroid/wiki

Now the more interesting part about how to use astroid itself is needed :)

**Comment by gauteh** [comment]
Great! that looks good! We should eventually add a custom sidebar to
navigate the tour.

**Comment by gauteh** [comment]
I put the old stuff into your organization, and copied the index into the sidebar. Feel free to re-organize. I didn't get around to fix the next-item in the list for the new sub-pages yet.

**Comment by gauteh** [comment]
I re-organized the README, now relying more heavily on your getting-started guide.

**Comment by gauteh** [comment]
@ff2000 could you please check if the docs are up-to-date after #74?
