### ISSUE TITLE
(feature) Integrate astroid: output email data and content to other tools

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#36]
I think it would make sense to make astroid output email data and content to ther tools. Astroid just needs of a way to enable this so that users can come up with scripts to glue with other tools (like a task manager).

For instance, see this script that can be used with mutt http://git.upsilon.cc/?p=utils/org-mutt.git;a=blob_plain;f=remember-mail;hb=HEAD

Astroid can already "save" an email  and it can already call scripts (like poll.sh) so it seems not far away from allowing this already.

Maybe also from the thread_index interface, we need a way to perform a user-defined action on the last email in the thread.

**Comment by gauteh** [comment]
This will be covered by #29.
