### ISSUE TITLE
configuration: how to hide certain tags?

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#38]
A lot of useful tags set by notmuch and/or astroid aren't necessarily useful to show all the time (e.g. replied, encrypted, signed, sent)

I think it makes sense to have a config variable `thread_index.cell.hidden_tags`.

**Comment by gauteh** [comment]
Yes, agreed. I already hide the tags where the information is shown otherwise: https://github.com/gauteh/astroid/blob/master/src/modes/thread_index/thread_index_list_cell_renderer.hh#L23

**Comment by apm256** [comment]
A great related feature would be to allow to "rename" tag, as it is possible with `alot`.

Example:

    [tags]
      [[signed]]
        translated = ''
      [[attachment]]
        translated = @

**Comment by gauteh** [comment]
apm256 writes on January 5, 2016 11:02:
> A great related feature would be to allow to "rename" tag, as it is possible with `alot`.
>
> Example:
>
>     [tags]
>       [[signed]]
>         translated = ''
>       [[attachment]]
>         translated = @
>

Yeah, I can see the use for that. The JSON config can at least handle this:

```
"astroid": {
  "tags": {
    "translate" : {
      "signed" : "",
      "encrypted" : "E",
    },
  },
},
...
```

They would have to be translated when:
- reading
- changing labels
- _not_ on standard labels (although they should be configurable: sent,
  unread, etc - but note that most of these have special meaning to
  notmuch)

(note that attachment is already visualized with an icon). We could even
have more user-configured icons:

```
"astroid": {
  "tags": {
    "icons" : {
      "signed" : "/path/to/icon.svg",
      "encrypted" : "standard-gtk-icon",
    },
  },
},
...
```

**Comment by apm256** [comment]
That would be perfect!

**Comment by hugoroy** [comment]
Maybe a little over the top :-) I prefer things to be more simplistic but it also allows for really nice, personal, specific stuff (like if you use your MUA to receive tons of bugzilla tickets and manage them with tags, this could be a nice interface to bug tracking).
