### ISSUE TITLE
(feature) forwarding as attachment

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#39]
It would be nice to deal with forwarding emails as attachment (opening them is bug #30).

For instance, right now, if I receive an HTML-only email and I try to forward it, the forwarded message will be empty except for a few headers.

**Comment by gauteh** [comment]
Yup. How would this best be accomplished? As a separate keybinding C-f? Then you can just change the default behaviour by swapping the keybindings.

**Comment by hugoroy** [comment]
True, but that seems like a little hack :-) 

So I think it makes sense to have this in the configuration file itself (inside mail.forward?).

**Comment by gauteh** [comment]
Set mail.forward.disposition to "attachment". At the moment there is no keybinding to choose which one, it always uses the config option.

**Comment by hugoroy** [comment]
↪ janvier 13, 2016 10:21 , Gaute Hope:
> Set mail.forward.disposition to "attachment". At the moment there is no keybinding to choose which one, it always uses the config option.

It works! ☺

**Comment by gauteh** [comment]
I am not sure if I include the message correctly, have you had any
experience with forwarded messages (attached) not arriving correctly?

**Comment by hugoroy** [comment]
No, it has worked well for me so far.
