### ISSUE TITLE
(feature) go to next unread thread in thread index

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#40]
(Sorry for launching so many issues and feature requests at you, I'm posting them as they go when I use astroid and I just mean to record them)

In the thread index view, I don't see any keybinding that will take me to the next unread thread. I think that would be useful.

For instance in mutt's mail folder view (which is equivalent to an index view in astroid for the user), Tab will automatically highlight the next unread email. So Tab+Enter will usually be a quick combination to read all unread emails in a folder.

**Comment by gauteh** [comment]
Hugo Roy writes on January 5, 2016 23:09:
> (Sorry for launching so many issues and feature requests at you, I'm posting them as they go when I use astroid and I just mean to record them)

No worries, I prefer it this way. Also then I know which features other
users miss the most.
 
> In the thread index view, I don't see any keybinding that will take me to the next unread thread. I think that would be useful.
> 
> For instance in mutt's mail folder view (which is equivalent to an index view in astroid for the user), Tab will automatically highlight the next unread email. So Tab+Enter will usually be a quick combination to read all unread emails in a folder.

Tets out #40. I removed the pane swap keybinding, I am considering to
drop panes since their function can be accomplished by using two windows
and I do not use them myself anymore. Comments?

**Comment by hugoroy** [comment]
I thought panes were nice. Although I don't use them for now, I think it would be sad to drop panes (especially for the future, when porting to systems where the windows manager sucks).

**Comment by gauteh** [comment]
Closed in #40, would be good with Shift-Tab to jump backwards, but need to update keybindings a little for that.

**Comment by hugoroy** [comment]
It works :) 

:+1:
