### ISSUE TITLE
(feature) persistent history of search queries

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#42]
When making a new query (with F by default), it doesn't seem to remember past queries. Making this persistent would be useful so that users can simply relaunch a recent query if it's complex enough to bother.

**Comment by gauteh** [comment]
Absolutely! If you feel adventurous, I'd be happy to receive a pull-request :beers: .

**Comment by hugoroy** [comment]
This is unlikely to happen. I know nothing of c plus plus.

If I had some vacation I would give it a try. But I'm not a developer so it's not something I might do by throwing just over a couple of hours at it.

However, if there's anything related to licensing, I could make a pull request (I'm an attorney).

**Comment by gauteh** [comment]
Ok, I appreciate the suggestions, debugging and wikiing. Hopefully,
there won't be any license issues :)

I realize c++ is not easiest to help out with.

**Comment by ff2000** [comment]
Where should those queries be stored? I think it's better to not touch a hand-crafted config file via code, so I would prefer e.g. a seperate simple plain text file where astroid stores those queries.
The other thing is: What actually IS history? Really everything in chronological order? Or is it OK to delete a query when you ran the same right now? (deduplication - I already had discussions about that ;)) I prefer deduplication. If it get's controversial should there be a config switch? (no deduplication; deduplication without reordering; deduplication with reordering - some more options?)

**Comment by gauteh** [comment]
I was looking at notmuch-hello for the emacs interface (https://notmuchmail.org/screenshots/), we could do something similar. Save the previous searches, and allow some to be saved (at some point). I also wanted to create a screen with an overview of tags with the number of messages in them, then the saved searches could go there. Anyway, that is a little more work.

I also think it should not be in the config file, keep say the last 100 in ~/.config/astroid/last_searches (or .cache/astroid/last_searches) and then possibly the saved searches in ~/.config/astroid/saved_searches (or the config file).

The most straightforward would probably be to just put everything in there, without worrying about duplication. If we do, I would prefer de-duplication with reordering.

**Comment by gauteh** [comment]
Search history implemented in #123.

**Comment by mardukbp** [comment]
@hugoroy In the search box you can use the up arrow to reuse recent queries. Hope this helps.

**Comment by gauteh** [comment]
Indeed, this is merged now.
