### ISSUE TITLE
`No such node (additional_sent_tags)`

### ISSUE THREAD

**Issue by aliceriot** [gauteh/astroid#53]
Hey folks,

I just built and installed Astroid on debian stretch. I had an Astroid config saved ([here](https://github.com/aliceriot/dotfiles/blob/master/astroid/config)) from a while ago which I was trying to use again (I switched back to Sup, got frustrated with things constantly breaking, so I'm trying this again).

When I first tried to start up Astroid using this config file I got the following error:

```
[info ] (12:16:12): welcome to astroid! - v0.4-135-g293c6f4c
[debug] (12:16:12): utf8: 1, UTF-8
[debug] (12:16:12): loading gtk..
[info ] (12:16:12): cf: loading: "/home/alice/.config/astroid/config"
[info ] (12:16:12): notmuch db: ~/mail/.notmuch
[info ] (12:16:12): date: init.
[info ] (12:16:12): ac: initializing accounts..
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::property_tree::ptree_bad_path> >'
  what():  No such node (additional_sent_tags)
```

it's looking for a property called `additional_sent_tags` on each instance of `account` in the config file. By adding this (just `additional_sent_tags: ""`) I was able to get the config to work.

I think maybe cleaning this up so that either the error message is more helpful, or so that Astroid just assumes that `additional_sent_tags: ""` if there isn't a specified value present would be great!

**Comment by gauteh** [comment]
Hi, the config should have been updated automatically. Hope it was fixed
in the commit above.

**Comment by aliceriot** [comment]
:100:
