### ISSUE TITLE
comments in `~/.config/astroid/keybindings`

### ISSUE THREAD

**Issue by aliceriot** [gauteh/astroid#67]
I just starting putting together a keybind file to bring Astroid more in line with the years of muscle memory I have from using Sup, Vim, and Vimium (chromium extension).

My file is here: https://github.com/aliceriot/dotfiles/blob/master/astroid/keybindings

I put some comments in on lines starting with `#`, it seems (judging by the output if I start astroid in my shell) that astroid is sort of ignoring those lines? But not really? I get something like this:

```
[ERROR] (08:52:41): ky: user bindings: too many parts in: switching
[debug] (08:52:41): ky: parsing line: between
[ERROR] (08:52:41): ky: user bindings: too many parts in: between
[debug] (08:52:41): ky: parsing line: buffers
[ERROR] (08:52:41): ky: user bindings: too many parts in: buffers
```

when parsing a line that looks like `# switching between buffers`.

Is there an officially supported way to add comments? I've got 30-something keybinds already, so it would be nice to organize them a little bit by grouping and having comments for headers.

Thanks!

**Comment by gauteh** [comment]
hope that fixes it!

**Comment by aliceriot** [comment]
it does! :+1:
