### ISSUE TITLE
crash on opening thread

### ISSUE THREAD

**Issue by aliceriot** [gauteh/astroid#68]
Just built current master, when I try to open a thread I get: 

```
[ERROR] (09:26:47): tv: cannot find html theme file: ui/thread-view.html, using default..
[ERROR] (09:26:47): tv: cannot find default html theme file.
```

config [here](https://github.com/aliceriot/dotfiles/tree/master/astroid).

(sorry for two issues in one morning!)

EDIT: I built it on Debian Unstable.

**Comment by gauteh** [comment]
Alice writes on January 18, 2016 15:31:
> Just built current master, when I try to open a thread I get: 
> 
> ```
> [ERROR] (09:26:47): tv: cannot find html theme file: ui/thread-view.html, using default..
> [ERROR] (09:26:47): tv: cannot find default html theme file.
> ```

Do you run ./astroid from the source root? If you run an uninstalled
version CWD must be the source root, e.g.:

~/.bin/astroid:
```
pushd path/to/src/astroid
./astroid $*
popd
```

**Comment by aliceriot** [comment]
Ah, I just did

```
$ scons --prefix=/usr build
$ scons --prefix=/usr install
```

and then launched the program with `dmenu`.

That does indeed fix it! I'll just write a little shell script.

**Comment by gauteh** [comment]
Outputting some more info in: https://github.com/gauteh/astroid/commit/e6e79cb4a03b8ed52f5a919f90d75eeb7bdefa2c, considering that fixed.
