### ISSUE TITLE
"cannot find ui file" with 'm'

### ISSUE THREAD

**Issue by apm256** [gauteh/astroid#69]
The new theme is very nice, but I don't understand how the ui files need to be organized.

1) When I run astroid with an empty `~/.config/astroid/ui`, I get:

    [debug] (13:45:11): theme: loading..
    [ERROR] (13:45:11): tv: cannot find html theme file: /home/apm/.config/astroid/ui/ui/thread-view.html, using default..
    [ERROR] (13:45:11): tv: cannot find default html theme file.

2) Then, I copy all the ui files in the directory:

    $ cp /usr/share/astroid/ui/* ~/.config/astroid/ui

as a result, astroid is running, but when I hit `m`, I get:

    [debug] (13:46:48): ky: Mode,  unknown key: m
    [debug] (13:46:48): ky: ThreadIndex mode,  unknown key: m
    [debug] (13:46:48): ky: MainWindow, handling: m (main_window.new_mail)
    [ERROR] (13:46:48): em: cannot find ui file.

**Comment by gauteh** [comment]
Did you re-compile astroid without the prefix setting?

**Comment by apm256** [comment]
I'm using the AUR package, when the "prefix" setting seems to be specified (as /usr):
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=astroid

**Comment by gauteh** [comment]
Either you compile astroid with a prefix in release mode, then you need
to install astroid and you will get ui files in:

  $ scons --prefix=PREFIX install

ui files go to:
  PREFIX/share/astroid/ui/*

or you build as debug, but then you need to run astroid from the source
directory:

  $ cd astroid.git/
  $ scons
  $ ./astroid

ui files are in:

  astroid.git/ui/*

in any case you can put your custom files (only html and scss file) in
~/.config/astroid/ui/*.

The glade file for the editor is not customizable and you need to either
install (with prefix) or run astroid from the source dir (without
compiling using a prefix).

**Comment by gauteh** [comment]
apm256 writes on January 19, 2016 14:12:
> I'm using the AUR package, when the "prefix" setting seems to be specified (as /usr):
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=astroid

What is the output of `pacman -Ql astroid-git` and `which astroid`?

**Comment by apm256** [comment]
$ pacman -Ql astroid
astroid /usr/
astroid /usr/bin/
astroid /usr/bin/astroid
astroid /usr/share/
astroid /usr/share/astroid/
astroid /usr/share/astroid/ui/
astroid /usr/share/astroid/ui/about.glade
astroid /usr/share/astroid/ui/edit-message.glade
astroid /usr/share/astroid/ui/no-mail.png
astroid /usr/share/astroid/ui/thread-view.html
astroid /usr/share/astroid/ui/thread-view.scss
$ which astroid
/usr/bin/astroid

**Comment by gauteh** [comment]
Indeed, PREFIX seems to have gotten lost in some code-cleanups (@ff2000: ehem..). Hopefully it works now?

**Comment by apm256** [comment]
It works: thank you!

**Comment by ff2000** [comment]
Excerpts from Gaute Hope's message of Januar 19, 2016 2:24 :
> Indeed, PREFIX seems to have gotten lost in some code-cleanups (@ff2000: ehem..). Hopefully it works now?

@gauteh Sorry for that, I'm just not that used to the build system...
Now every commit compiles again 3 files (more than 20 sec. here) even
when they are not changed.
I had an idea today: wouldn't it be better to pass at least PREFIX by
CXXFLAGS? That would reduce the forced compilations by two, again.
Doing the same thing with GIT_DESC might not work, because it would
require detection for use in the compilation units. PREFIX usually stays
the same while GIT_DESC changes with every commit
Do you think that could work?

**Comment by gauteh** [comment]
I think we could put both GIT_DESC and PREFIX in CXXFLAGS, I have
usually done that for other projects, this just seemed like a cleaner
approach. But, I don't mind changing it.
