### ISSUE TITLE
FOSDEM demo

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#75]
Hi,

Just wanted to know who was going to be at FOSDEM next weekend. Maybe we could arrange some time to demonstrate astroid to some of the mutt/notmuch users ;-)

**Comment by aureooms** [comment]
I will be there too

**Comment by gauteh** [comment]
Hugo Roy writes on January 23, 2016 19:39:
> Hi,
> 
> Just wanted to know who was going to be at FOSDEM next weekend. Maybe we could arrange some time to demonstrate astroid to some of the mutt/notmuch users ;-)
> 

Unfortunately I won't be able to go, crashing with another conference.
Would be cool if you found time and want to demo it :)

**Comment by gauteh** [comment]
Send me some photos or something in that case!

**Comment by gauteh** [comment]
Did any of you go?

**Comment by hugoroy** [comment]
I had a laptop charger problem so I couldn't demo :-(

**Comment by gauteh** [comment]
Hugo Roy writes on February 4, 2016 16:18:
> I had a laptop charger problem so I couldn't demo :-(

Ok, too bad.

**Comment by aureooms** [comment]
I had to leave for the weekend.
