### ISSUE TITLE
Quit: Yes/No buttons don't work

### ISSUE THREAD

**Issue by hugoroy** [gauteh/astroid#77]
I notice that quitting now shows this:

![capture d ecran de 2016-02-07 16-04-46](https://cloud.githubusercontent.com/assets/1629771/12873065/96700756-cdb4-11e5-802e-26beb35513c7.png)

but I can't click on them (and there's nothing to show in the console).

**Comment by gauteh** [comment]
Hugo Roy writes on February 7, 2016 16:05:
> I notice that quitting now shows this:
> 
> ![capture d ecran de 2016-02-07 16-04-46](https://cloud.githubusercontent.com/assets/1629771/12873065/96700756-cdb4-11e5-802e-26beb35513c7.png)
> 
> but I can't click on them (and there's nothing to show in the console).

You can use the 'y' or 'n' keys as well. But it should possible to use
the mouse now as well, it does not work perfectly when there are several
windows, but the keys should still work.

**Comment by hugoroy** [comment]
↪ février 7, 2016 6:29 , Gaute Hope:
> 
> You can use the 'y' or 'n' keys as well. But it should possible to use
> the mouse now as well, it does not work perfectly when there are several
> windows, but the keys should still work.

Yes, I'm using the y/n keys, but as far as I can tell the buttons
sometimes don't work at all.

**Comment by gauteh** [comment]
Hugo Roy writes on February 8, 2016 0:05:
> Yes, I'm using the y/n keys, but as far as I can tell the buttons
> sometimes don't work at all.

Ok, the buttons didn't work with the mouse until the last fix. Let me
know if you still encounter the issue (and any information on which mode
you're in when it happens and so on is very useful).
