### ISSUE TITLE
scons install: default prefix is not used

### ISSUE THREAD

**Issue by teto** [gauteh/astroid#79]
After doing `sudo scons install` and running astroid, it looks for files in $HOME apparently:
```
[info ] (13:56:25): poll: emitted poll state: 0
[info ] (13:56:25): poll: emitted poll state: 0
[info ] (13:56:28): ti_list: loading: 0000000000004446
[debug] (13:56:28): ti: open thread: 0000000000004446 (1)
[debug] (13:56:28): theme: loading..
[ERROR] (13:56:28): tv: cannot find html theme file: /home/teto/ui/thread-view.html, using default..
[ERROR] (13:56:28): tv: cannot find default html theme file.
```
which makes astroid stop. If I run astroid from its repo `$HOME/astroid$ ./astroid` then it works.

**Comment by gauteh** [comment]
Hi, this is a bit illogical I agree. You need to either specify the --prefix where you install astroid or you need to make a wrapper script to launch astroid from the source directory:

```sh
#! /bin/bash

pushd ~/dev/mail/notm/astroid
./astroid $* | tee ~/.config/astroid/log
popd

```

**Comment by gauteh** [comment]
The behaviour should be more logical now.

Note that I changed the default prefix from /usr to /usr/local. astroid
will now only check for local resource files, that is in the current
dir, if compiled with debug flags (default, turn off with
--release=something).

-gaute

**Comment by gauteh** [comment]
Or: --debug=False (for scons)

**Comment by teto** [comment]
thanks, reinstalled and that fixed it :)
