### ISSUE TITLE
Change list view font

### ISSUE THREAD

**Issue by dontdieych** [gauteh/astroid#80]
```json
    "thread_index": {
        "page_jump_rows": "6",
        "sort_order": "newest",
        "cell": {
            "font_description": "monospace",
            "line_spacing": "4",
            "date_length": "10",
            "message_count_length": "4",
            "authors_length": "20",
            "tags_length": "80",
            "subject_color": "#807d74",
            "subject_color_selected": "#000000",
            "tags_color": "#31587a",
            "hidden_tags": "attachment,flagged,unread"
        }
```

If I change font to other than default I got this,

![2016-02-12-125250_1440x900_scrot](https://cloud.githubusercontent.com/assets/6509673/12998492/9ee4b8ba-d187-11e5-9da8-283cf73e88d9.png)

How could I change font or style of list view?

BTW, I'm very much enjoying read mail mainly because astroid. Please don't add many things in UI.

Thanks.

**Comment by gauteh** [comment]
Thanks,

It turns out that if you don't specify a font-size it is set to 0,
probably using a default from somewhere when actually rendering. I added
a warning about that. You can fix it by using a font_description like:
"monospace 9".

**Comment by dontdieych** [comment]
Thanks, It works like a charm.
