### ISSUE TITLE
color in thread view

### ISSUE THREAD

**Issue by emdete** [gauteh/astroid#84]
the color used for the selected mail in the thread view (border on the left) is different for uncollapsed mails. it irritited me alot and i suggest to use the same color to make the gui easier to understand. the line that creates this is:

ui/thread-view.scss:198 border-left-color: lighten( $focused-solid, 33% );

if the lighten() is removed it's as i would expect it.

**Comment by gauteh** [comment]
@hugoroy: I know you already know about this, but ping anyway.

**Comment by hugoroy** [comment]
Hi @emdete 

This is indeed how I wanted it to be, so at least it's not a bug :-) The rationale for this is to make it more comfortable to read uncollapsed mail. A lighter color is easier on the eye. 

I think it would be good to have the opinion of a trained designer on this. @jancborchardt what do you think about this?

**Comment by hugoroy** [comment]
![2016-02-27 15-56-52](https://cloud.githubusercontent.com/assets/1629771/13373572/63bcef06-dd6b-11e5-8d0c-f990d0400bff.png)

![2016-02-27 15-56-48](https://cloud.githubusercontent.com/assets/1629771/13373573/68683330-dd6b-11e5-9d3e-da347832d296.png)

**Comment by jancborchardt** [comment]
I have not used the program, but from looking at the screenshots the colors should definitely match. Otherwise it’s quite confusing. The darker blue seems fine, as the light one is barely visible.

**Comment by gauteh** [comment]
Thanks, fixed.
