### ISSUE TITLE
keybindings in regard of scrolling should be more consistent

### ISSUE THREAD

**Issue by emdete** [gauteh/astroid#86]
a keybinging thread_index.page_down and thread_index.page_up (while PgUp/PgDown work). it seems as well as if bindings in the config file are not checked (they seem to be ignored silently). the page_up/down functionality should move the selection as well to make navigation more intuitive. many such navigations follow vi, some do not. for example PgUp/Down should be C-u/d. 

finally the navigation in the thread view should not jump between the objects, it jumps from mail navigation to element navigation which seems to be wrong to me.

btw: it's really sad that "function keys" can't be mapped from the config. i really would like to see C-Tab and C-S-Tab switch between the windows (b/B binding). can that be done in code?

**Comment by gauteh** [comment]
M. Dietrich writes on February 21, 2016 19:44:
> a keybinging thread_index.page_down and thread_index.page_up (while PgUp/PgDown work). it seems as well as if bindings in the config file are not checked (they seem to be ignored silently). the page_up/down functionality should move the selection as well to make navigation more intuitive. many such navigations follow vi, some do not. for example PgUp/Down should be C-u/d. 

thread_index.page_* should be implemented, could change default for C-J
and C-K to C-d and C-u.

> finally the navigation in the thread view should not jump between the objects, it jumps from mail navigation to element navigation which seems to be wrong to me.

You think it should follow more of a tree structure?

You can use n/p to only jump between messages, and then use j/k to jump
between all elements.

> btw: it's really sad that "function keys" can't be mapped from the config. i really would like to see C-Tab and C-S-Tab switch between the windows (b/B binding). can that be done in code?

Absolutely, this should be implemented.

**Comment by emdete** [comment]
> thread_index.page_* should be implemented, could change default for C-J and C-K to C-d and C-u.

these are not generated by get_keys.py so i added those manually with no success.

> You think it should follow more of a tree structure?

to be honest i don't know. i just know that the current behaviour irritated me alot. maybe the bug (selection is not visible sometimes) and the light color of the selection were causes for that as well. i would expect the element navigation would not leave the selected mail but cycle in this mail. big problem is paging of a long, selected mail in opposite to change the selection... but having four different down/next funktions is making me headache.

**Comment by gauteh** [comment]
M. Dietrich writes on February 21, 2016 21:56:
>> thread_index.page_* should be implemented, could change default for C-J and C-K to C-d and C-u.
> 
> these are not generated by get_keys.py so i added those manually with no success.

get_keys gets the targets that are defined in the source code, if you
add them yourself they wont mean anything to astroid since there is no
code associated with them.

**Comment by gauteh** [comment]
M. Dietrich writes on February 21, 2016 19:44:
> a keybinging thread_index.page_down and thread_index.page_up (while PgUp/PgDown work). it seems as well as if bindings in the config file are not checked (they seem to be ignored silently). the page_up/down functionality should move the selection as well to make navigation more intuitive. many such navigations follow vi, some do not. for example PgUp/Down should be C-u/d. 

This is fixed.

> finally the navigation in the thread view should not jump between the objects, it jumps from mail navigation to element navigation which seems to be wrong to me.

I guess this is a design choice, I agree it is not intuitive wihout
using astroid for a while: 

What about a configuration option to make
focus cycle within each message (when using j/k and C-j/C-k), then you
have to use n/p to get to the next message.

> btw: it's really sad that "function keys" can't be mapped from the config. i really would like to see C-Tab and C-S-Tab switch between the windows (b/B binding). can that be done in code?

This issue should be fixed in #94, please test.

**Comment by emdete** [comment]
not yet, if you reconfigure the binding the pagedown gets lost and falls back to some system default which does not move the selection.

furthermore the pagedown at the end of the list behaves differently than the cursordown: while the first down not expand, the latter expands the list of items

**Comment by gauteh** [comment]
M. Dietrich writes on February 29, 2016 23:33:
> not yet, if you reconfigure the binding the pagedown gets lost and falls back to some system default which does not move the selection.

You have to bind Page down again too, the aliases are discarded if there
is a user binding.

 
> furthermore the pagedown at the end of the list behaves differently than the cursordown: while the first down not expand, the latter expands the list of items

Yes, we should handle mouse-scroll too. Anyway, let's see what happens
with #95.

**Comment by gauteh** [comment]
Issue fixed by #95.
