### ISSUE TITLE
view raw mail from received mails doesnt work

### ISSUE THREAD

**Issue by emdete** [gauteh/astroid#88]
while i can use 'V' to view mails that i just created i can't do so on received mails. it just shows a white window. would be nice to have that fixed because i often read the whole headers.

**Comment by gauteh** [comment]
I think it is an encoding issue, probably not too hard to fix. I think it
occurs when putting the Mail content into the gtk buffer.

Den mandag 22. februar 2016 skrev M. Dietrich <notifications@github.com>
følgende:

**Comment by gauteh** [comment]
Could you check if 7186f1b0218c27707f81e121fd4fcf1b07a890e5 fixes the
issue?

-g
